name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: make -C ci build

    - name: Build examples
      run: make -C ci build-examples

    - name: Check fmt
      run: make -C ci check-fmt

    - name: Check clippy lints
      run: make -C ci check-clippy

    - name: Run tests
      run: make -C ci check-tests

    - name: Run example tests
      run: make -C ci check-examples

    - name: Run examples
      run: make -C ci run-examples
