name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose

    - name: Build examples
      run: cargo build --verbose --examples

    - name: Check fmt
      run: cargo fmt --check

    - name: Run tests
      run: cargo test --verbose

    - name: Run example tests
      run: cargo test --examples --verbose
