name: tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always
  NIX_DEV: nix develop ./examples/rv32i-guest --command

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build
      run: make -C ci build

    - name: Build examples
      run: $NIX_DEV make -C ci build-examples

    - name: Check fmt
      run: make -C ci check-fmt

    - name: Check clippy lints
      run: make -C ci check-clippy

    - name: Run tests
      run: make -C ci check-tests

    - name: Run example tests
      run: make -C ci check-examples

    - name: Run examples
      run: $NIX_DEV make -C ci run-examples
